version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 10.105.16.22
      DB_PORT: 5432
      DB_NAME: postgress
      DB_USER: app_user
      DB_PASSWORD: redhat

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
